### ISSUE TITLE
请问我遇到这个错误

### ISSUE THREAD

**Issue by RockyQu** [XieEDeHeiShou/MVPHelper#2]
https://github.com/githubwing/MVPHelper/issues/20
AS版本已经是2.3 3.0 都不行

**Comment by DevDengChao** [comment]
收到. 晚上我试试看.

**Comment by RockyQu** [comment]
在Issues也有遇到的，查了一天没找出原因，我只建了一个AnAction

**Comment by DevDengChao** [comment]
无法复现该 Bug:
![android-studio-sample](https://user-images.githubusercontent.com/16363180/37709799-4f50f774-2d46-11e8-9b6d-db44da148dda.gif)
![idea-sample](https://user-images.githubusercontent.com/16363180/37709819-6680507a-2d46-11e8-9f8a-ea8eed2a7681.gif)
我这边用 Android Studio 测试的时候出现过一次插件异常, 是测试插件时, 在沙盒中运行的Android Studio 不包含 File Template 导致的, 因为插件在运行过程中会调用默认的/项目制定的 java class 模板 以及 java interface 模板.
如果你那边确实每次都会报异常的话, 加我qq吧. 2325690622
